// Graph Language

graph t = "TEST"

main {
    print "START"

    graph gr = "new graph 1"
    graph gr2 = "new graph 2"
    vertex b = "B"
    vertex c = "C"
    edge e = <b,c>

    gr <- b, a , v, d
    gr -> c , a, b , d

    if (b == a){
        print "b == a"
    }
    if (b != a) {
        print "b != a"
    }

    if (gr <?> a) {
        print "GR CONTAIN A"
    } else if (gr is graph){
        print "GR not contain A and is GRAPH"
    } else {
        print "GR not contain A and is not GRAPH"
    }

    print "FINISH"
}

